### ISSUE TITLE
Set new_val = old_val + 1

### ISSUE THREAD

**Issue by MrNghia123** [henhal/dynamodb-expressions#3]
Sorry If I missed something. I could not find how to do this

Set new_val = old_val + 1

**Comment by MrNghia123** [comment]
I meant set an attribute from another attribute
SET attribute2 = attribute1

**Comment by henhal** [comment]
Hi @MrNghia123!

Sorry for not having ideal documentation.

Your first example for `new_val = old_val + 1` works like this:

```
{
  new_val: UpdateAction.set(SetValue.add('old_val', 1))
}
```

However, looking at my code I can interestingly not find any way to simply copy a value from one attribute to another. That's indeed something that should be added.

However, perhaps the most common case for this would be to use `SetValue.ifNotExists`, since it does copy another attribute but also assigns a default value if that attribute does not exist. Could that work as a workaround?

```
{
  attribute2: UpdateAction.set(SetValue.ifNotExists('attribute1', 0)
}
```

Maybe I even deliberately left out the simple copy operator since it fails if the source attribute does not exist, so wrapping such a copy in a `if_not_exists` is a good idea.

**Comment by henhal** [comment]
Hi again @MrNghia123!

My apologies, I realized the answer to your question was much easier, you simply use prefix a  referred attribute with `#`:

```
{
  attribute2: '#attribute1'
}
```

This is somewhat described under "pitfalls" in the README: https://github.com/henhal/dynamodb-expressions/?tab=readme-ov-file#namevalue-ambiguities

Thanks

**Comment by MrNghia123** [comment]
Hi @henhal . Thank you for really helpful information, and such helpful package!
I did figure it out about the # prefix, but your tip to use the if_not_exists to avoid error is awesome.

Best regards,

**Comment by henhal** [comment]
Thanks! 
I ended up creating [some more unit tests](https://github.com/henhal/dynamodb-expressions/blob/main/test/UpdateAction.test.ts#L140) for these special cases - and I actually found a bug also regarding special characters in attribute names, so that's been fixed now.

I'm closing this issue. Have a nice day!
